# Generated by Django 5.1.1 on 2025-04-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_us', models.CharField(blank=True, max_length=50, null=True)),
                ('developer_name', models.CharField(blank=True, max_length=50, null=True)),
                ('zone_or_village', models.CharField(max_length=50)),
                ('road_name', models.CharField(choices=[('high_court', 'High Court Road'), ('buremba', 'Buremba Road'), ('mbaguta', 'mbaguta Road'), ('makhansingh', 'makhansingh Road'), ('mc_Alister', 'mc_Alister Road'), ('constintino', 'constintino Road'), ('akiki_nyabongo', 'Akiki Nyabongo Road'), ('ntare', 'Ntare Road'), ('bucunku', 'Bucunku Road'), ('stanley', 'Stanley Road'), ('rwizi', 'Rwizi Road'), ('ruharo', 'Ruharo Road'), ('mosque', 'mosque Road'), ('upper_circular', 'Upper Circular Road'), ('victor_bwana', 'Victor Bwana Road')], max_length=50)),
                ('division', models.CharField(blank=True, max_length=50, null=True)),
                ('opposite_property_no', models.CharField(blank=True, max_length=50, null=True)),
                ('structure_photo', models.ImageField(upload_to='structure_photos')),
                ('submission_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
