# Generated by Django 5.1.1 on 2025-04-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concern',
            name='zone_or_village',
            field=models.CharField(choices=[('ntare', 'Ntare'), ('rwizi', 'Rwizi'), ('ruharo', 'Ruharo')], max_length=50),
        ),
    ]
