# Generated by Django 5.1.1 on 2025-04-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_concern_zone_or_village'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concern',
            name='division',
            field=models.CharField(blank=True, choices=[('high_court', 'High Court Road'), ('buremba', 'Buremba Road'), ('mbaguta', 'mbaguta Road'), ('makhansingh', 'makhansingh Road'), ('mc_Alister', 'mc_Alister Road'), ('constintino', 'constintino Road'), ('akiki_nyabongo', 'Akiki Nyabongo Road'), ('ntare', 'Ntare Road'), ('bucunku', 'Bucunku Road'), ('stanley', 'Stanley Road'), ('rwizi', 'Rwizi Road'), ('ruharo', 'Ruharo Road'), ('mosque', 'mosque Road'), ('upper_circular', 'Upper Circular Road'), ('victor_bwana', 'Victor Bwana Road')], max_length=50, null=True),
        ),
    ]
